# promote_tier_data.ps1 -- move the v1.5 tier golden references into fpga/sim/ (C line)
#
# WHY THIS SCRIPT EXISTS
#   The two pixel-source tiers (720p60 = 3/8, 1080p45 = 1/4) have their golden
#   references generated by gen_motion_vectors.py / gen_frames.py.  They were
#   generated into TEMPORARY directories at the repo root because, in the DSH
#   sandbox this work was done in, only the repo root is writable by processes;
#   fpga/ and its subdirectories deny writes (see docs/24 section 1.4).
#
#   That leaves the tiers' data in temp dirs, so whoever signs off v1.5 cannot
#   just re-run the HLS flow -- they would first have to find and regenerate
#   everything.  This script performs that promotion reproducibly, and
#   VERIFIES it byte-for-byte (SHA256), so a partial copy cannot go unnoticed.
#
# USAGE (run from anywhere; needs write permission to fpga/sim/)
#   powershell -NoProfile -ExecutionPolicy Bypass -File fpga\promote_tier_data.ps1
#   ... -SourceRoot D:\Desktop\AMD      # where the _golden*/_roi*/_fir* dirs live
#   ... -WhatIfOnly                     # report what would be copied, copy nothing
#
# ENCODING: ASCII only on purpose.  Windows PowerShell 5.1 decodes a BOM-less
#   .ps1 as GBK; non-ASCII text then decodes into bytes that break the parser.
#   If you must add non-ASCII, save the file as UTF-8 WITH BOM.

param(
    [string]$SourceRoot = (Split-Path -Parent $PSScriptRoot),
    [switch]$WhatIfOnly
)

$ErrorActionPreference = 'Continue'
$repo = Split-Path -Parent $PSScriptRoot
$dstRoot = Join-Path $repo 'fpga\sim'

# source dir (under -SourceRoot)  ->  destination dir (under fpga/sim)
# These are temporary dirs from the tier work; the destination names are the
# canonical ones (docs/26 section 6.4) and match run_hls.tcl's VIGILENS_TIER map.
$plan = @(
    @{ src = '_golden720';    dst = 'data_motion_720p60';  note = '720p60 gray/motion golden (480x270)' },
    @{ src = '_golden1080';   dst = 'data_motion_1080p45'; note = '1080p45 gray/motion golden (480x270)' },
    @{ src = '_roi720';       dst = 'data_roi_720p';       note = 'roi_statistic golden @1280x720' },
    @{ src = '_roi1080';      dst = 'data_roi_1080p';      note = 'roi_statistic golden @1920x1080' },
    @{ src = '_golden720s';   dst = 'data_motion_small_720p60'; note = 'small-size 3/8 (motion csim fits the budget)' },
    @{ src = '_golden3_8';    dst = 'data_motion_small_3_8';    note = 'small-size 3/8 for rgb2gray cosim' },
    @{ src = '_fir30_small';  dst = 'data_fir_small_30hz';      note = 'small-size FIR series matching the 30 Hz table' }
)

# Files that must never travel: they are logs/hosts of the run, not data.
$skipNames = @('README.md')

function Get-Sha256([string]$p) {
    (Get-FileHash -Algorithm SHA256 -Path $p).Hash
}

Write-Host '=== promote tier golden references into fpga/sim/ ==='
Write-Host "repo       = $repo"
Write-Host "sourceRoot = $SourceRoot"
Write-Host "dest root  = $dstRoot"
Write-Host ''

$copied = 0
$skipped = 0
$failed = @()
$verified = 0

foreach ($p in $plan) {
    $s = Join-Path $SourceRoot $p.src
    $d = Join-Path $dstRoot $p.dst
    Write-Host ("--- {0}  ->  {1}   ({2})" -f $p.src, $p.dst, $p.note)

    if (-not (Test-Path $s)) {
        Write-Host "    [skip] source not present (already promoted, or never generated)"
        $skipped++
        continue
    }

    $files = Get-ChildItem -Path $s -File -Recurse | Where-Object { $skipNames -notcontains $_.Name }
    if ($files.Count -eq 0) {
        Write-Host "    [skip] no data files in source"
        $skipped++
        continue
    }

    if (-not $WhatIfOnly) {
        if (-not (Test-Path $d)) {
            try {
                New-Item -ItemType Directory -Path $d -Force -ErrorAction Stop | Out-Null
            } catch {
                Write-Host ("    [FAIL] cannot create destination: {0}" -f $_.Exception.Message)
                $failed += $p.dst
                continue
            }
        }
    }

    foreach ($f in $files) {
        $target = Join-Path $d $f.Name
        $rel = "$($p.dst)/$($f.Name)"
        if ($WhatIfOnly) {
            Write-Host ("    [whatif] {0}  ({1} B)" -f $rel, $f.Length)
            continue
        }
        $srcHash = Get-Sha256 $f.FullName
        try {
            Copy-Item -LiteralPath $f.FullName -Destination $target -Force -ErrorAction Stop
        } catch {
            Write-Host ("    [FAIL] copy {0}: {1}" -f $rel, $_.Exception.Message)
            $failed += $rel
            continue
        }
        # VERIFY: a copy that is not byte-identical is worse than no copy, because
        # the HLS testbenches compare with tolerance 0 and would report "the IP is
        # wrong" instead of "the data is wrong".
        if (-not (Test-Path $target)) {
            Write-Host ("    [FAIL] verify {0}: target missing after copy" -f $rel)
            $failed += $rel
            continue
        }
        $dstHash = Get-Sha256 $target
        if ($dstHash -ne $srcHash) {
            Write-Host ("    [FAIL] verify {0}: SHA256 differs" -f $rel)
            Write-Host ("           src={0}" -f $srcHash)
            Write-Host ("           dst={0}" -f $dstHash)
            $failed += $rel
            continue
        }
        Write-Host ("    [ok]     {0}  ({1} B, sha256 {2})" -f $rel, $f.Length, $srcHash.Substring(0, 12))
        $copied++
        $verified++
    }
}

Write-Host ''
Write-Host '=== summary ==='
Write-Host ("  copied+verified = {0}" -f $copied)
Write-Host ("  dirs skipped    = {0}  (source absent / no data)" -f $skipped)
Write-Host ("  failures        = {0}" -f $failed.Count)
foreach ($x in $failed) { Write-Host ("    FAILED: " + $x) }

if ($WhatIfOnly) {
    Write-Host ''
    Write-Host '[whatif] nothing was written.'
    exit 0
}

if ($failed.Count -gt 0) {
    Write-Host ''
    Write-Host 'RESULT: FAIL -- some files did not copy or did not verify.'
    Write-Host 'If the failures are access-denied under fpga/sim/, that is the sandbox'
    Write-Host 'write restriction (docs/24 section 1.4): run this script in a terminal'
    Write-Host 'that is allowed to write under fpga/sim/.'
    exit 1
}

Write-Host ''
Write-Host 'RESULT: PASS -- tier data is in place and byte-identical.'
Write-Host 'Next: each destination dir has a README.md describing the files and the'
Write-Host 'exact regenerate command; re-run the HLS flow with VIGILENS_TIER set.'
exit 0
